#!/usr/bin/env ruby

git_url("git@gitlab.seebche.com:sibche/ios/sibche-certificates.git")
git_branch("master")
clone_branch_directly(true)

type("development") # The default type, can be: appstore, adhoc, enterprise or development

app_identifier(["com.musicify.production"])
username("sib.fastlane@gmail.com") # Your Apple Developer Portal username
#readonly(true)

# For all available options run `fastlane match --help`
# Remove the # in the beginning of the line to enable the other options
